In [1]:
import tensorflow as tr

# create Tensorflow Constant

In [2]:
hello = tr.constant("hello")

In [3]:
hello

<tf.Tensor 'Const:0' shape=() dtype=string>

In [4]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [17]:
sess = tr.Session()

In [18]:
sess.run(hello)

b'hello'

In [19]:
number = tr.constant(100)

In [20]:
sess.run(number)

100

# some operation on constant using TensorFlow

In [21]:
a = tr.constant(12)

In [22]:
b = tr.constant(6)

In [23]:
with tr.Session() as sess:
    print(f"Addition : {sess.run(a+b)}")
    print(f"Substraction : {sess.run(a-b)}")

Addition : 18
Substraction : 6


# create PlaceHolder using Tensorflow

In [24]:
x = tr.placeholder(tr.int32)
y = tr.placeholder(tr.int32)

In [25]:
d = {x:12,y:6}

In [31]:
with tr.Session() as sass:
    print(f"Addition : {sass.run(tr.add(x,y),d)}")
    print(f"Substraction : {sass.run(tr.subtract(x,y),d)}")
    print(f"Multiplay : {sass.run(tr.multiply(x,y),d)}")

Addition : 18
Substraction : 6
Multiplay : 72


In [33]:
# Now let's see an example of a more complex operation, using Matrix Multiplication. First we need to create the matrices:

In [34]:
import numpy as np

In [35]:
a = np.array([[5,5]])

In [36]:
a

array([[5, 5]])

In [37]:
b = np.array([[2],[2]])

In [38]:
b

array([[2],
       [2]])

In [39]:
mat_a = tr.constant(a)
mat_b = tr.constant(b)

In [40]:
sess = tr.Session()

In [41]:
sess.run(tr.matmul(mat_a,mat_b))

array([[20]])

# Great Job!