# NumPy Arrays

In [2]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [3]:
import numpy as np

In [5]:
# One Dimension Array

arr = np.array(my_list)
arr

array([1, 2, 3, 4, 5])

In [6]:
# To Dimension Array

my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# Create Array using arange function
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
# Create The Array Of Zeros 

In [11]:
# One Dimension Array 
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
# Two Dimension Array
np.zeros((5,5))
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
# Create Array of Ones 

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [17]:
# linspace : it is used when particular boundar divide for some part
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [18]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [19]:
# Identity Matrix 

In [20]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [26]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
# Matrix generate using random method

In [37]:
# random.rand gives number between 0 to 1 excusive
np.random.rand(5)

array([0.47799968, 0.46504467, 0.81692686, 0.11311255, 0.34320245])

In [38]:
np.random.rand(2)

array([0.41006385, 0.80220568])

In [41]:
# randn method is used for the random any number positive or negative
np.random.randn(2)

array([-2.25706757,  0.49774719])

In [42]:
np.random.randn(5)

array([ 0.75160826,  0.11894012, -0.96007454, -0.20837809,  0.96354985])

In [64]:
np.random.randint(0,100,10)

array([70, 75,  7, 92, 58, 55, 33, 32, 46, 15])

In [65]:
np.random.randint(0,50,(3,3))

array([[44, 12, 11],
       [36,  9, 17],
       [ 1, 46, 47]])

In [66]:
np.random.randint(0,10,(10,10))

array([[9, 3, 4, 5, 7, 7, 3, 9, 7, 1],
       [2, 2, 3, 2, 2, 8, 0, 7, 3, 5],
       [9, 8, 5, 9, 1, 6, 7, 7, 9, 3],
       [0, 6, 0, 5, 3, 7, 3, 1, 6, 3],
       [3, 7, 6, 0, 7, 0, 2, 3, 2, 7],
       [7, 5, 6, 9, 7, 8, 6, 8, 7, 2],
       [9, 1, 7, 4, 6, 2, 6, 6, 2, 0],
       [7, 5, 4, 0, 8, 5, 8, 7, 5, 3],
       [0, 8, 8, 4, 6, 0, 3, 3, 8, 2],
       [5, 0, 6, 4, 0, 3, 0, 8, 2, 7]])

In [67]:
# Reshape Of The Array and not loose any element if loose then get error

In [69]:
arr = np.random.randint(0,10,25)
arr

array([6, 1, 4, 9, 0, 3, 0, 0, 9, 7, 8, 7, 5, 4, 7, 4, 4, 7, 0, 4, 5, 0,
       8, 4, 8])

In [71]:
reshape = arr.reshape(5,5)
reshape

array([[6, 1, 4, 9, 0],
       [3, 0, 0, 9, 7],
       [8, 7, 5, 4, 7],
       [4, 4, 7, 0, 4],
       [5, 0, 8, 4, 8]])

In [72]:
reshape.max()

9

In [73]:
reshape.min()

0

In [75]:
# Give the index of the max Number
reshape.argmax()

3

In [76]:
reshape.argmin()

4

In [81]:
# Rows and columns return
reshape.shape
arr.shape

(25,)

In [82]:
arr.dtype

dtype('int32')