# Numpy Indexing and Selection

In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[10]

10

In [6]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[5::2]

array([5, 7, 9])

In [10]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [11]:
arr[:-3]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [12]:
copy_arr = arr[0:5]
copy_arr

array([0, 1, 2, 3, 4])

In [16]:
# Bordcast all the value
copy_arr[:] = 100
copy_arr
arr
# Change the value of the both array

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [17]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
copy_arr = arr.copy()
copy_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
copy_arr[0:6] = 100
copy_arr
arr
# Here When copy the arry the not change the value of the both array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Two Dimension Array

In [21]:
arr_2d = [[1,2,3],[4,5,6],[7,8,9]]
arr_2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [22]:
arr_np = np.array(arr_2d)
arr_np

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr_np[0][0]
arr_np[2][2]

9

In [26]:
# Using Another Way to fetch the data 
# arrarr_np[row,column]

arr_np[0,0]
arr_np[2,2]

9

In [28]:
arr_np

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
# Fetch the subsection of the array
arr_np[:2,1:]

array([[2, 3],
       [5, 6]])

In [30]:
arr_np[1:,1:]

array([[5, 6],
       [8, 9]])

In [31]:
# Create The more complex array and fetch the subsection of the array

In [33]:
matrix = np.random.randint(5,25,(8,8))
matrix

array([[10, 11, 12, 23, 22, 13, 10,  9],
       [18, 22, 12, 19, 17, 23, 15,  8],
       [ 6, 21, 13,  9,  9, 17, 10,  7],
       [ 5, 23, 10,  9, 20, 17, 13, 23],
       [ 5, 21,  8, 18, 14, 21, 14, 20],
       [16, 12, 10, 11, 13, 19, 16, 24],
       [14, 19,  8, 19, 11, 21, 22, 22],
       [ 8, 11, 23, 24, 24, 18, 13,  8]])

In [34]:
matrix[:4,:4]

array([[10, 11, 12, 23],
       [18, 22, 12, 19],
       [ 6, 21, 13,  9],
       [ 5, 23, 10,  9]])

In [35]:
matrix[4:,4:]

array([[14, 21, 14, 20],
       [13, 19, 16, 24],
       [11, 21, 22, 22],
       [24, 18, 13,  8]])

In [38]:
matrix[3:5,2:4]

array([[10,  9],
       [ 8, 18]])

In [39]:
# Conadtion In Array 

In [40]:
my_array = np.arange(0,11)
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
# Two Step Process 
boll_arr = my_array > 5
my_array[boll_arr]

array([ 6,  7,  8,  9, 10])

In [44]:
my_array[my_array < 4]

array([0, 1, 2, 3])

In [45]:
my_array[my_array % 2 == 0]

array([ 0,  2,  4,  6,  8, 10])

In [46]:
my_2dArray = np.arange(0,25).reshape(5,5)
my_2dArray

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
my_2dArray[my_2dArray % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])